### ISSUE TITLE
WinDLL include issue for Santec DLLs

### ISSUE THREAD

**Issue by tpr0p** [QPG-MIT/slmsuite#9] opened 2023-01-11 18:48 UTC
OS: Windows 10 Home
Python: 3.8.8
Conda: 4.10.3

https://github.com/QPG-MIT/slmsuite/blob/ac24e5221c370a02e4a007eaf39fa01750d10f03/slmsuite/hardware/slms/_slm_win.py#L30

WinDLL requires full path to `_libname = "C:\...\SLMFunc.dll"`, can't do relative `_libname = "SLMFunc.dll"`.

**Comment by ichristen** [comment] 2023-01-13 04:52
I suspect the issue was some failure with `os.getcwd()` involving the two slmsuite installations in the above situation. Would need to reproduce again.

https://github.com/QPG-MIT/slmsuite/blob/ac24e5221c370a02e4a007eaf39fa01750d10f03/slmsuite/hardware/slms/_slm_win.py#L26

**Comment by ichristen** [comment] 2023-01-13 17:27
Also noting that the `pip install slmsuite` was failing in the case.

**Comment by ichristen** [comment] 2023-01-13 21:01
Probably fixed in #13 (see addition of `abspath(__file__)`). Will reopen if the problem reappears.

**Comment by ichristen** [comment] 2023-06-06 21:06
Hi @lufermar ,

A few questions and a suggestion:

- Are you using the pypy (`pip install slmsuite`) version of slmsuite, or using a local github version (`git clone`)?
- Could you send the full error trace?
- Did you copy the .dll files (SLMFunc.dll, FTD3XX.dll) provided by Santec anywhere (usually they will send a USB drive with the SLM)?
- You might try copying them into either your current Python runtime directory or the slmsuite.hardware.slms path (please see [this](https://github.com/QPG-MIT/slmsuite/blob/a977cfcf5eaf79d4fc702ef23a617c961fa83f79/slmsuite/hardware/slms/santec.py#LL5C1-L5C1) and [this](https://github.com/QPG-MIT/slmsuite/blob/a977cfcf5eaf79d4fc702ef23a617c961fa83f79/slmsuite/hardware/slms/santec.py#L31))

Best,
Ian

**Comment by ichristen** [comment] 2023-06-06 22:30
@lufermar , as a last comment, could you also check whether the Santec-provided GUI (installer included on the USB) is working. This will help eliminate OS- or system- related issues. What OS are you using?

**Comment by lufermar** [comment] 2023-06-07 09:39
Dear @ichristen,
I solved the problem, but let me try to answer everything just in case someone else has the same issue:

- I use the pipe
- I copied the .dll files
- I copied BOTH FILES in BOTH FOLDERS

The GUI worked and I am using Windows 10.
Best,
Luis

**Comment by ichristen** [comment] 2023-06-07 15:32
Hi @lufermar ,

Just for our info, does it really not work if the files are not copied into both? I find this surprising because the .dlls should be loaded into the python runtime when the `slmsuite.hardware.slms.santec` file is imported, and this should be a one-time thing and look for the .dlls in one directory. We will also edit the docs to make this procedure more clear. Is there anything that we can put into the error message that would help?

Best,
Ian

**Comment by lufermar** [comment] 2023-06-08 05:50
Hi @ichristen,
that's the least I can do. If I copy BOTH .dll files:

1. in MY current Python runtime directory AND the slmsuite.hardware.slms path it WORKS
2. ONLY in MY current Python runtime directory it WORKS
3. ONLY in the slmsuite.hardware.slms path it DOESN'T WORK

I get the error message when I execute the cell in Jupyter that imports `Santec`. The message I receive is:
`santec.py: Santec DLLs not installed. Install these to use Santec SLMs. ... (this is the message from the script)... 
Original error: could not find module 'SLMFunc.dll' (or one of its dependencies). Try using the full path with constructor syntax`.

Hope it helps,
L

**Comment by ichristen** [comment] 2023-06-08 17:27
Okay, @tpr0p, so it seems that the runtime directory is most important under `pip` install. We should modify the docs to reflect this.

- [ ] Modify current docs to correct for `pip` behavior.
- [ ] Look into a default install directory option for .dlls. It seems that many open-source packages opt to make sure the .dlls are in the current path, but maybe there's a more elegant option.

**Comment by lufermar** [comment] 2023-06-19 07:42
@ichristen,
I tried to see if the issue (https://github.com/QPG-MIT/slmsuite/issues/9#issuecomment-1581930053) happened with another laptop and it seems that in this case you just need to follow the tutorial that you provide and not my recommendation. I will see if I can see why. Hope this information helps.

**Closed** 2024-04-03 19:52 UTC
Labels: bug, v0.0.2
